{{- if and (.Values.namespaces) (.Values.teamInstancesAreClusterScoped) }}
{{- range $ns := .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: {{ $ns }}-argocd-application-controller
    app.kubernetes.io/part-of: {{ $.Values.namespaces | first }}
  name: {{ $ns }}-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.namespaces | first }}-argocd-application-controller
subjects:
- kind: ServiceAccount
  name: {{ $.Values.name }}-argocd-application-controller
  namespace: {{ $ns }}
{{- end }}
{{- end }}
