---
operator:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  sourceName: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-pipelines-operator-rh.v1.8.0
